function merchantPage(){const m=state.merchants.find(x=>x.id===state.selectedMerchant)||state.merchants[0];const orders=state.orders.filter(o=>o.merchantId===m.id&&!['DELIVERED','SETTLED','CANCELLED'].includes(o.status));return shell(`<section class="page"><div class="status-bar"><div><div class="tiny muted">PAINEL DA REVENDA</div><h1 class="page-title" style="margin-bottom:2px">${m.name}</h1></div><span class="status-pill ${m.online?'online':'offline'}">${m.online?'● ONLINE':'OFFLINE'}</span></div><div class="card flat form-stack"><div class="input-wrap"><label>Operação demonstrada</label><select class="input" onchange="selectMerchant(this.value)">${state.merchants.map(x=>`<option value="${x.id}" ${x.id===m.id?'selected':''}>${x.name}</option>`).join('')}</select></div><button class="${m.online?'secondary':'primary'}" onclick="toggleOnline('${m.id}')">${m.online?'Pausar pedidos':'Ficar online'}</button></div>
<section class="section"><div class="merchant-kpis"><div class="kpi"><span class="label">Preço P13</span><strong>${BRL.format(m.priceP13)}</strong></div><div class="kpi"><span class="label">Estoque P13</span><strong>${m.stock}</strong></div><div class="kpi"><span class="label">Trust</span><strong>${m.trust}</strong></div><div class="kpi"><span class="label">Pedidos ativos</span><strong>${orders.length}</strong></div></div></section>
<div class="card flat form-stack"><div class="field-row"><div class="input-wrap"><label>Preço P13</label><input id="m-price" type="number" step="0.10" class="input" value="${m.priceP13}"></div><div class="input-wrap"><label>Estoque disponível</label><input id="m-stock" type="number" class="input" value="${m.stock}"></div></div><button class="secondary" onclick="merchantUpdate('${m.id}')">Confirmar preço e estoque</button></div>
<section class="section"><div class="section-head"><div><h2>Pedidos que exigem ação</h2><p>Aceitar significa assumir compromisso real de atendimento.</p></div></div>${orders.length?orders.map(o=>merchantOrder(o)).join(''):`<div class="empty card">Nenhum pedido ativo para esta revenda.</div>`}</section></section>`)}
function merchantOrder(o){const copy=statusCopy[o.status]||[o.status,''];const items=Object.entries(o.cart).filter(([,q])=>q>0).map(([k,q])=>`${q}× ${products[k].name}`).join(' • ');let actions='';if(o.status==='OFFERED_TO_MERCHANT')actions=`<button class="primary small" onclick="merchantAction('${o.id}','accept')">Aceitar</button><button class="danger-btn small" onclick="merchantAction('${o.id}','reject')">Não consigo atender</button>`;else if(o.status==='MERCHANT_ACCEPTED'||o.status==='PREPARING')actions=`<button class="primary small" onclick="merchantAction('${o.id}','dispatch')">Confirmar saída</button>`;else if(o.status==='OUT_FOR_DELIVERY')actions=`<button class="secondary small" onclick="merchantAction('${o.id}','arriving')">Estou chegando</button>`;else if(o.status==='ARRIVING')actions=`<input id="pin-${o.id}" class="input" style="height:40px;max-width:120px" placeholder="PIN"><button class="primary small" onclick="merchantAction('${o.id}','deliver')">Confirmar entrega</button>`;return `<div class="order-card ${o.status==='OFFERED_TO_MERCHANT'?'new':''}"><div class="order-head"><div><div class="order-id">${o.id}</div><div class="order-line">${items}</div></div><div style="text-align:right"><strong>${BRL.format(o.total)}</strong><div class="tiny muted">${copy[0]}</div></div></div><div class="order-line">📍 ${o.address}</div><div class="order-actions">${actions}</div></div>`}
function selectMerchant(id){state.selectedMerchant=id;save();render()}
function toggleOnline(id){const m=state.merchants.find(x=>x.id===id);m.online=!m.online;save();render();toast(m.online?'Revenda online':'Revenda pausada')}
function merchantUpdate(id){const m=state.merchants.find(x=>x.id===id);const price=Number(document.querySelector('#m-price').value);const stock=Number(document.querySelector('#m-stock').value);if(price<=0||stock<0)return toast('Valores inválidos');m.priceP13=price;m.stock=stock;m.priceConfirmedAt=now().toISOString();save();render();toast('Preço e estoque confirmados')}
function addEvent(o,status,title,desc){o.status=status;o.events.push({status,time:now().toISOString(),title,desc})}
function merchantAction(id,action){const o=state.orders.find(x=>x.id===id);const m=state.merchants.find(x=>x.id===o.merchantId);if(action==='accept'){m.accepted++;addEvent(o,'MERCHANT_ACCEPTED','Revenda confirmou ✓','A revenda confirmou preço, itens e capacidade de entrega.');addEvent(o,'PREPARING','Em preparação','Estoque reservado para este pedido.');m.stock=Math.max(0,m.stock-(o.cart.P13||0));toast('Pedido aceito e estoque reservado')}
if(action==='reject'){o.events.push({status:'REASSIGNING',time:now().toISOString(),title:'Buscando outra revenda',desc:'A primeira opção não conseguiu atender.'});const candidates=state.merchants.filter(x=>x.id!==m.id&&x.online&&x.stock>0&&cartAvailable(x));if(candidates.length){const n=[...candidates].sort((a,b)=>a.eta-b.eta)[0];o.merchantId=n.id;o.status='OFFERED_TO_MERCHANT';o.events.push({status:'OFFERED_TO_MERCHANT',time:now().toISOString(),title:'Novo parceiro acionado',desc:'Outra revenda recebeu o pedido para confirmação.'});toast('Pedido reatribuído automaticamente')}else{addEvent(o,'CANCELLED','Pedido cancelado','Nenhum parceiro disponível para a cesta neste momento.');toast('Sem parceiro alternativo') }}
if(action==='dispatch'){addEvent(o,'OUT_FOR_DELIVERY','Saiu para entrega ✓','A revenda confirmou explicitamente a saída do pedido.');toast('Cliente agora vê “A caminho”')}
if(action==='arriving'){addEvent(o,'ARRIVING','Entregador chegando','Chegada próxima confirmada na demonstração.');toast('Status atualizado')}
if(action==='deliver'){const pin=document.querySelector('#pin-'+id)?.value.trim();if(pin!==o.pin)return toast('PIN incorreto — entrega não pode ser concluída');addEvent(o,'DELIVERED','Entregue ✓','PIN validado com sucesso.');m.delivered++;state.user.purchases++;state.user.cashback=Number((state.user.cashback+1.25).toFixed(2));setTimeout(()=>{addEvent(o,'SETTLED','Pedido concluído','Entrega conciliada; benefícios liberados conforme regras.');save()},400);toast('Entrega comprovada e cashback gerado')}
save();render()}

function merchantOrders(){state.mode='merchant';save();return merchantPage()}
function catalog(){const m=state.merchants.find(x=>x.id===state.selectedMerchant)||state.merchants[0];return shell(`<section class="page"><h1 class="page-title">Meu catálogo</h1><p class="muted">A revenda não fica limitada ao P13. Cada produto tem preço e disponibilidade próprios.</p><div class="list">${Object.entries(products).map(([k,p])=>{const val=k==='P13'?m.priceP13:m.products[k];return `<div class="list-row"><div class="product-left"><div class="product-icon">${p.icon}</div><div><strong>${p.name}</strong><br><small>${val==null?'Não oferecido':BRL.format(val)}</small></div></div><span class="status-pill ${val==null?'offline':'online'}">${val==null?'INATIVO':'ATIVO'}</span></div>`}).join('')}</div><div class="notice" style="margin-top:14px">No produto real, cada categoria terá regras de compatibilidade logística e conformidade próprias.</div></section>`)}
function merchantMetrics(){const m=state.merchants.find(x=>x.id===state.selectedMerchant)||state.merchants[0];return shell(`<section class="page"><h1 class="page-title">Desempenho</h1><div class="merchant-kpis"><div class="kpi"><span class="label">Trust Score</span><strong>${m.trust}/100</strong></div><div class="kpi"><span class="label">Aceitos</span><strong>${m.accepted}</strong></div><div class="kpi"><span class="label">Entregues</span><strong>${m.delivered}</strong></div><div class="kpi"><span class="label">Preço divergente</span><strong>0</strong></div></div><section class="section"><div class="card flat"><h3>O que mais pesa no Trust Score</h3><div class="list"><div class="list-row"><strong>Entregas dentro do ETA</strong><span>25%</span></div><div class="list-row"><strong>Conclusão após aceite</strong><span>20%</span></div><div class="list-row"><strong>Integridade dos status</strong><span>15%</span></div><div class="list-row"><strong>Integridade de preço</strong><span>15%</span></div></div></div></section></section>`)}